# 서버 포트, 센서 임계값, 핀 번호 등
# do not use korean in any section or value. (path, ...) 

[Network]
# (IMPORTANT) SERVER_IP = RPI_IP !!!
SERVER_IP=100.82.189.43
SERVER_PORT=60003

# Pin Number Must Based on BCM
[Hardware]
LED_GPIO_PIN=17
BUZZER_GPIO_PIN=27
CDS_I2C_ADDR=0x48

# Anode, 8pins: a~f and dp
SEGMENT_GPIO_PINS=13,19,16,20,21,6,5,26

[RaspberryPi]
RPI_USER=raspberry
RPI_IP=100.82.189.43
RPI_DEST=~/veda/project_linux
